In [17]:
import tensorflow as tf

In [18]:
daily_sales=[20,25,-60,18,23,-41,35]

In [19]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [20]:
for sales in tf_dataset:
    print(sales.numpy())

20
25
-60
18
23
-41
35


In [21]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

20
25
-60
18
23
-41
35


In [22]:
for sales in tf_dataset.take(4):
    print(sales.numpy())

20
25
-60
18


In [23]:
tf_dataset=tf_dataset.filter(lambda x:x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

20
25
18
23
35


In [24]:
tf_dataset=tf_dataset.map(lambda x:x*83)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1660
2075
1494
1909
2905


In [25]:
tf_dataset=tf_dataset.shuffle(3)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

2075
1494
1660
2905
1909


In [26]:
for sales_batch in tf_dataset.batch(3):
    print(sales_batch.numpy())

[1660 1909 2075]
[1494 2905]


In [28]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales)
tf_dataset=tf_dataset.filter(lambda x:x>0).map(lambda y:y*83).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1660 1494]
[2075 1909]
[2905]


In [35]:
image_ds=tf.data.Dataset.list_files("vehicle/*/*",shuffle=False)

for file in image_ds.take(3):
    print(file.numpy())

b'vehicle\\car\\1.jpg'
b'vehicle\\car\\10.jpg'
b'vehicle\\car\\11.jpg'


In [37]:
image_ds=image_ds.shuffle(80)

for file in image_ds.take(3):
    print(file.numpy())

b'vehicle\\car\\25.jpg'
b'vehicle\\plane\\30.jpg'
b'vehicle\\car\\42.jpg'


In [38]:
image_count=len(image_ds)
image_count

100

In [39]:
train_size=int(image_count*0.8)

train_ds=image_ds.take(train_size)
test_ds=image_ds.skip(train_size)

In [40]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path,os.path.sep)[-2]

In [41]:
for i in train_ds.take(4):
    print(i.numpy())

b'vehicle\\plane\\14.jpg'
b'vehicle\\plane\\2.jpg'
b'vehicle\\plane\\48.jpg'
b'vehicle\\car\\19.jpg'


In [42]:
for label in train_ds.map(get_label):
    print(label)

tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'car', shape=(), dtype=string)
tf.Tensor(b'car'

In [43]:
def process_image(file_path):
    label=get_label(file_path)
    
    img=tf.io.read_file(file_path)
    img=tf.image.decode_jpeg(img)
    img=tf.image.resize(img,(128,128))
    
    return img,label

In [47]:
for img,label in train_ds.map(process_image).take(2):
    print("image: ",img)
    print("label: ",label)

image:  tf.Tensor(
[[[127.640625 135.64062  138.64062 ]
  [148.375    156.375    159.375   ]
  [154.9375   162.9375   165.9375  ]
  ...
  [150.73438  151.73438  143.73438 ]
  [156.96875  157.96875  149.96875 ]
  [154.35938  155.35938  147.35938 ]]

 [[ 92.515625 100.515625 103.515625]
  [ 90.4375    98.4375   101.4375  ]
  [103.234375 111.234375 114.234375]
  ...
  [149.46875  150.46875  142.46875 ]
  [147.5      148.5      140.5     ]
  [145.70312  146.70312  138.70312 ]]

 [[ 92.953125 100.953125 103.953125]
  [ 92.1875   100.1875   103.1875  ]
  [ 88.90625   96.90625   99.90625 ]
  ...
  [155.48438  156.48438  148.48438 ]
  [152.75     153.75     145.75    ]
  [152.375    153.375    145.375   ]]

 ...

 [[252.28125  252.15625  247.15625 ]
  [253.07812  252.95312  247.95312 ]
  [252.3125   252.1875   247.1875  ]
  ...
  [210.1875   214.1875   215.1875  ]
  [210.51562  214.51562  215.51562 ]
  [221.64062  225.64062  226.64062 ]]

 [[182.82812  181.82812  176.82812 ]
  [178.70312  177.